### ISSUE TITLE
Error while compiling tnvme

### ISSUE THREAD

**Issue by Rajnikantcmr** [nvmecompliance/tnvme#24]
i will explain you my situation,i am trying to execute tnvme on Ubntu 14.04 LTS version with NVMe hardware present on host machine.

i did not use the complete concept which mentioned in the readmelist,because i do not need emulator.so,i skipped all the step related to virtual box,server and qemu.so,i just executed only library file, tnvme, dnvme and manage.

i am able to compile dnvme,but while compling tnvme i am getting eroor like this:

make -C GrpAdminCreateIOQCmd all
make[1]: Entering directory `/home/unigen/Desktop/nvme/tnvme/tnvme-master/
GrpAdminCreateIOQCmd'
g++                 -I. -I../ -I../../ -I/usr/local/include -O0 -W -Wall -Werror -std=c++0x  -lboost_filesystem -lboost_system -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml++-2.6 -I/usr/lib/libxml++-2.6/include  -lxml++-2.6 -lxml2 -lglibmm-2.4 -lgobject-2.0 -lsigc-2.0 -lglib-2.0    -c grpAdminCreateIOQCmd.cpp -o grpAdminCreateIOQCmd.o -lm
In file included from ../tnvme.h:23:0,
                 from ../group.h:22,
                 from grpAdminCreateIOQCmd.h:20,
                 from grpAdminCreateIOQCmd.cpp:17:
../dnvme.h:22:32: fatal error: dnvme/dnvme_ioctls.h: No such file or directory
 #include "dnvme/dnvme_ioctls.h"
                                ^
compilation terminated.
make[1]: *** [grpAdminCreateIOQCmd.o] Error 1
make[1]: Leaving directory `/home/unigen/Desktop/nvme/tnvme/tnvme-master/GrpAdminCreateIOQCmd'
make: *** [GrpAdminCreateIOQCmd] Error 2

Anyone here who knows,please guide me.WIll be waiting for your reply.

Thanks
Rajnikant

**Comment by mbogochow** [comment]
The dnvme directory must be in the same parent directory as the tnvme directory.  Your directory structure should therefore be similar to the following:

|-nvme
   |---tnvme
   |---dnvme
   |---manage

**Comment by Rajnikantcmr** [comment]
yes i followed this step.i did it in the same way.as you mentioned still i did not.please can you explain my error in elaborate form.

**Comment by Rajnikantcmr** [comment]
@mbogochow i did not got my answer,so please keep this thread open and let other help me.Guys,still i am looking for an answer.

**Comment by mbogochow** [comment]
This error is thrown if tnvme cannot find the dnvme source files.  It checks for those files in the ../dnvme directory relative to the tnvme directory.  Looking at your log, you are compiling from some tnvme/tnvme-master/ directory so unless you placed the dnvme directory in the tnvme directory, it will not be able to find the dnvme source.

If you clone each of the nvmecompliance repos each with their own subdirectory in the same parent directory like shown in my previous post and then change to the tnvme directory and compile with the make command you will not see this error.

**Comment by Rajnikantcmr** [comment]
Thanks @mbogochow  for explaining,still i am facing same problem.i went through all issue and figured out,this can also be one reason "The Compliance suite only works on 64 bit Linux operating systems with kernel versions equal or greater than 2.6 but less than 3.0. Ubuntu 13.04 has a kernel version of 3.8."

**Comment by mbogochow** [comment]
tnvme has since been updated to work with kernels up to 4.0 so that should not be an issue.

If you put the following into a shell script file and run it then it should pull the nvmecompliance source from GitHub and compile it successfully:

```shell
#!/bin/bash

DIR="./nvmecompliance-githubdebug"

if [ ! -d "$DIR" ]; then
  mkdir $DIR
fi
pushd $DIR
rm -rf tnvme dnvme manage
git clone https://github.com/nvmecompliance/dnvme.git
git clone https://github.com/nvmecompliance/tnvme.git
git clone https://github.com/nvmecompliance/manage.git
pushd dnvme
make
popd
pushd tnvme
make
popd
popd
```

**Comment by Rajnikantcmr** [comment]
Hi Mike, i tried the way u asked me.sory for asking u again and again.check the log file i got after executing it.i have saved my script file in nvme.sh script file:
unigen@unigen-All-Series:~$ ./nvme.sh 
~/nvmecompliance-githubdebug ~
Cloning into 'dnvme'...
remote: Counting objects: 2108, done.
remote: Total 2108 (delta 0), reused 0 (delta 0), pack-reused 2108
Receiving objects: 100% (2108/2108), 2.72 MiB | 298.00 KiB/s, done.
Resolving deltas: 100% (1328/1328), done.
Checking connectivity... done.
Cloning into 'tnvme'...
remote: Counting objects: 7107, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7107 (delta 0), reused 0 (delta 0), pack-reused 7103
Receiving objects: 100% (7107/7107), 7.10 MiB | 236.00 KiB/s, done.
Resolving deltas: 100% (4759/4759), done.
Checking connectivity... done.
Cloning into 'manage'...
remote: Counting objects: 463, done.
remote: Total 463 (delta 0), reused 0 (delta 0), pack-reused 463
Receiving objects: 100% (463/463), 4.79 MiB | 111.00 KiB/s, done.
Resolving deltas: 100% (243/243), done.
Checking connectivity... done.
~/nvmecompliance-githubdebug/dnvme ~/nvmecompliance-githubdebug ~
make -C /lib/modules/3.13.0-24-generic/build/ M=/home/unigen/nvmecompliance-githubdebug/dnvme modules
make[1]: Entering directory `/usr/src/linux-headers-3.13.0-24-generic'
  CC [M]  /home/unigen/nvmecompliance-githubdebug/dnvme/sysdnvme.o
  CC [M]  /home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_ioctls.o
  CC [M]  /home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_reg.o
  CC [M]  /home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_sts_chk.o
  CC [M]  /home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_queue.o
  CC [M]  /home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_cmds.o
  CC [M]  /home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_ds.o
  CC [M]  /home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_irq.o
/home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_irq.c: In function ‘dnvme_pci_enable_msi’:
/home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_irq.c:656:5: error: implicit declaration of function ‘pci_enable_msi_range’ [-Werror=implicit-function-declaration]
     ret = pci_enable_msi_range(dev, nvec, nvec);
     ^
cc1: some warnings being treated as errors
make[2]: *** [/home/unigen/nvmecompliance-githubdebug/dnvme/dnvme_irq.o] Error 1
make[1]: *** [_module_/home/unigen/nvmecompliance-githubdebug/dnvme] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.13.0-24-generic'
make: *** [all] Error 2
~/nvmecompliance-githubdebug ~
~/nvmecompliance-githubdebug/tnvme ~/nvmecompliance-githubdebug ~
make -C GrpAdminCreateIOQCmd all
Package libxml++-2.6 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml++-2.6.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libxml++-2.6' found
make[1]: Entering directory `/home/unigen/nvmecompliance-githubdebug/tnvme/GrpAdminCreateIOQCmd'
g++				 -I. -I../ -I../../ -I/usr/local/include -O0 -W -Wall -Werror -std=c++0x  -lboost_filesystem -lboost_system   -c grpAdminCreateIOQCmd.cpp -o grpAdminCreateIOQCmd.o -lm
make[1]: g++: Command not found
make[1]: *** [grpAdminCreateIOQCmd.o] Error 127
make[1]: Leaving directory `/home/unigen/nvmecompliance-githubdebug/tnvme/GrpAdminCreateIOQCmd'
make: *** [GrpAdminCreateIOQCmd] Error 2
~/nvmecompliance-githubdebug ~
~
can you please share me your mail/skype id and your time of availability.so that i can explain why i am not able to get through.i really need to close this by today/tommorow.Please pleas.......help me out.

Thanks
Rajnikant

**Comment by mbogochow** [comment]
I have uploaded a possible fix to dnvme.  Also it looks like you do not have all of the required packages for tnvme.  Run the following command to install the missing package:

sudo apt-get install -y libxml++2.6-dev libxml++2.6-doc

After, try rerunning the script again to see if you encounter anymore issues.

**Comment by Rajnikantcmr** [comment]
Hi Mike
 if u have complete set up,will you explain me or can share.i can come online and will listen to u.is that possible.

**Comment by mbogochow** [comment]
I sent info to the email listed in your GitHub account.

**Comment by Rajnikantcmr** [comment]
i received your message.and sent request to add me on your contact list
"rajnikantcmrb"

On 5 June 2015 at 22:51, Mike Bogochow <notifications@github.com> wrote:

> I sent info to the email listed in your GitHub account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nvmecompliance/tnvme/issues/24#issuecomment-109369061>
> .
>



-- 
Thanks and Regard
    RAJNIKANT

**Comment by mbogochow** [comment]
Issue resolved after installing all required packages.
